# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build

    - name: Run Coverage
      run: |
        chmod +x gradlew
        ./gradlew test jacocoTestReport
        
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: /home/runner/work/factoria-ci/factoria-ci/build/reports/tests/test/index.html
        token: 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
        min-coverage-overall: 40
        min-coverage-changed-files: 60
          
    - name: Send mail
      if: ${{ always() }}
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.freesmtpservers.com
        server_port: 25
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        # email body as text
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        # comma-separated string, send email to
        to: francisco.v@thoughtworks.com
        # from email name
        from: francisco.v@thoughtworks.com

